title: RAD SOFTWARE
baseurl: /
permalink: "/:title/"
collections:
  posts:
    permalink: "/posts/:title/"
palette: blue
header:
  title: RAD SOFTWARE
  logo_img: images/logo.png
  has_nav: true
  menu:
    actions:
      - label: Contact
        url: /contact
footer:
  logo_img: images/logo_alt.png
  tagline: Custom Software Development, Sydney
  has_nav: true
  nav_title: Services
  has_social: false
  social_title: Community
  has_subscribe: false
  subscribe_title: Subscribe
  subscribe_content: Stay up to date with our latest developments.
  content: "&copy; RAD SOFTWARE. All rights reserved."
  # links:
  # - text: Made with Stackbit
  #   url: "https://www.stackbit.com"
  #   new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
