# generates a sitemap
[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  # buildDir = "_site"
  prettyURLs = true
  exclude = [
    # By file Path
    './build-dir/path-to/file.html',
    # By Glob pattern
    '**/**/child-one.html'
  ]

# checks internal links are valid
[[plugins]]
package = "netlify-plugin-checklinks"

# 301 (default): Permanent redirect.
# 302: Temporary redirect.
# 404: Not found

[[redirects]]
  from = "/articles/default.aspx"
  to = "/"
  status = 404
[[redirects]]
  from = "/articles/dataaccesslayerdesign1.aspx"
  to = "/"
  status = 404
[[redirects]]
  from = "/articles/google-pagerank.aspx"
  to = "/"
  status = 404
[[redirects]]
  from = "/web/Products/RegexDesigner/Default.aspx"
  to = "/regexdesigner/"
  status = 301
[[redirects]]
  from = "/web/CodeZone/Articles/ClipboardMonitor.aspx"
  to = "/articles/clipboardmonitor.aspx/"
  status = 301
[[redirects]]
  from = "/nextgeneration/*"
  to = "/codegenerator/"
  status = 301
[[redirects]]
  from = "/codegenerator/Next*"
  to = "/codegenerator/"
  status = 301
